name: Expo EAS Build (disabled)

on:
  # Désactivé temporairement: aucune exécution automatique ni manuelle
  workflow_call:

jobs:
  disabled:
    if: false
    runs-on: ubuntu-latest
    steps:
      - run: echo "Expo EAS workflow désactivé temporairement"
